### ISSUE TITLE
after hitting the TAB key the editor work in confusing way

### ISSUE THREAD

**Issue by wfranzini** [NorfairKing/smos#12]
After hitting tab the edit behave in a confused way.  You can view with your own eyes at
https://asciinema.org/a/URMJ8AsswGK1ztaLloCg65R20

**Comment by NorfairKing** [comment]
Hey! This is an interesting problem to bump into.
It's because brick expects on-screen strings to not contain tabs.
I'm not sure how to solve it yet.
A few options:
- disallow tabs in any text that gets to screen
- transform on-screen text with `'\t' -> ' '`

What do you think @jtdaugherty ?

**Comment by jtdaugherty** [comment]
I'm not sure how you'd like me to contribute. How can I help?

**Comment by NorfairKing** [comment]
@jtdaugherty. What is the recommended way of displaying tabs in brick? Or are tabs just best not allowed?

**Comment by jtdaugherty** [comment]
In general I suggest sanitizing the input of tabs so that they don't cause layout problems. If tabs are important in your application, then I suggest converting them to spaces at input time. That way the spaces will get rendered as expected, and your application can determine the appropriate width conversion.

**Comment by NorfairKing** [comment]
Ok thanks @jtdaugherty.

@wfranzini to keep backward compatibility and to not mess with copy-pasting ability, I am making a little change where tabs are displayed as spaces but no data is modified.

**Comment by NorfairKing** [comment]
@wfranzini Could you try out 133104d4e5fe54b59c0d214cece9d8fd9fb2d4df and let me know if it fixes your issues?

**Comment by wfranzini** [comment]
@NorfairKing it seems OK to me.  Thanks!
