### ISSUE TITLE
Document the fuzzy time parsing

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#124]
This should include all the options for what can be parsed.
More info here: https://github.com/NorfairKing/fuzzy-time/blob/master/fuzzy-time/src/Data/FuzzyTime/Parser.hs

**Comment by ketzacoatl** [comment]
@NorfairKing are you looking for haddocks on each of those functions, or is there a different place/format for the docs to add?

**Comment by NorfairKing** [comment]
@ketzacoatl I'm thinking on the docs site: see `smos-docs-site`.
