### ISSUE TITLE
Breakout tree to new smos file

### ISSUE THREAD

**Issue by polyrod** [NorfairKing/smos#126]
I see the need for a  feature of breaking out a entry in a smos file and to put it in a new smos file or make it a new project.
Saw the "Copy-pasting a node/tree #17"-Issue , maybe could be combined. Thanks

**Comment by NorfairKing** [comment]
This is a good point! I haven't needed to use this but I've seen other people wanting to do this.
I think it can only be combined with #17 if https://github.com/NorfairKing/smos/issues/63 is done first.

**Comment by polyrod** [comment]
what about extending smos/src/Smos/Actions/File.hs to have "smart" create-actions , that check for existing names/directories,
like createNewSmosFile :: Path Abs File -> SmosM (Either SmosFileCreateError ()) , so in case of an error it could be handled by the TUI ?

**Comment by NorfairKing** [comment]
@polyrod I'm less worried about the way to handle things behind the scenes because that's just code.
What I'm worried about is the UX here. I put some concerns in #63 . They're all fixable but I need to get to it :)

If you want to try it out, I'd be happy to review a PR!
