### ISSUE TITLE
The 'now' line in the agenda report is in the incorrect place in the morning

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#129]
I noticed this around 02:00.

**Comment by NorfairKing** [comment]
This is where that happens: https://github.com/NorfairKing/smos/blob/master/smos-query/src/Smos/Query/Commands/Agenda.hs#L113

**Comment by ketzacoatl** [comment]
@NorfairKing are there tests we could define to help us track this down? Can you help me define those scenarios?

**Comment by NorfairKing** [comment]
Here: https://github.com/NorfairKing/smos/blob/master/smos-report/src/Smos/Report/Agenda.hs
It _may_ be fixed already, but a test to verify that would be nice nonetheless.
Tests are in https://github.com/NorfairKing/smos/blob/master/smos-report-gen/test/Smos/Report/AgendaSpec.hs
