### ISSUE TITLE
Launching `smos` TUI without existing ~/workflow directory fails silently

### ISSUE THREAD

**Issue by cgeorgii** [NorfairKing/smos#148]
Hi! Came across an issue when trying to go through the documentation. Changing this might help with user friendliness and reduce friction when getting started.

### Current behavior
Issuing `smos` without an existing `~/workflow` folder on the command line causes... nothing.

### Expected behavior
Tool should either fail loudly and instruct the user to create the directory or create the directory if it has permission to do so.

**Comment by NorfairKing** [comment]
Hi @cgeorgii Thanks for the issue.
I can't seem to reproduce this:

```
export SMOS_WORKFLOW_DIR=~/hello/world && smos
```
and
```
export HOME=/hello/world && smos
```

This works fine...

**Comment by NorfairKing** [comment]
@cgeorgii You are right about how this could affect friction with first-time users, so I wrote these tests just to be sure:
https://github.com/NorfairKing/smos/blob/291f59a50e3fc27b954b1c2c3110aee81c23e2ef/smos/test/Smos/LaunchSpec.hs

It looks like everything should be working as intended ...

**Comment by cgeorgii** [comment]
Hey @NorfairKing this is really weird. I could reproduce it a few times last night after a fresh install but it seems to work as intended after creating the directory even if I remove it again. Does smos keep files anywhere? 🤔 

Anyway, the tests seem to cover it, so I'll close the issue. I'll report back if I can reproduce it!

**Comment by NorfairKing** [comment]
@cgeorgii Smos keeps some files in `~/.smos` and some in `.local/share/smos` (I still have to consolidate those.)
