### ISSUE TITLE
Reaching invalid `No file selected` state makes smos unresponsive

### ISSUE THREAD

**Issue by cgeorgii** [NorfairKing/smos#150]
## Current behavior
Reaching the screen prevents the user from doing anything ~, even quitting the program with `q`~.

## Expected behavior
- According to[ this discussion](https://github.com/NorfairKing/smos/issues/142#issuecomment-679999454), the screen should not be reachable at all.

## Steps to reproduce

1. Start smos from the CLI using the `smos` executable and see this screen:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/12649588/91173159-a9d9b700-e6dd-11ea-9c2e-61b603ade280.png">

2. Open the browser for projects/archived items with `ba` or `bp` and since I don't have any projects or files in here, I see the following screen:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/12649588/91172935-4c456a80-e6dd-11ea-84ce-3efd22fd716b.png">

3. Pressing `ESC` on this screen leads to the following screen and nothing else can be done. Quitting doesn't work, help doesn't work, nothing works:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/12649588/91173056-7c8d0900-e6dd-11ea-840a-6b0ffdc59561.png">

4. The only possible action at this point is to restart the terminal.

**Comment by NorfairKing** [comment]
I've been thinking about this.
What _should_ be the proper behaviour here? 
Should quitting get you back to the editor that you originally opened?

**Comment by NorfairKing** [comment]
I think I managed to fix this on development. Please try it out and let me know if this issue should be closed.
