### ISSUE TITLE
A way to delete timestamps

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#159]
There is no way to delete timestamps at the moment.

Changes will be necessary in these places:

- The timestamps cursor: https://github.com/NorfairKing/smos/blob/master/smos-cursor/src/Smos/Cursor/Timestamps.hs 
- The timestamps actions: https://github.com/NorfairKing/smos/blob/master/smos/src/Smos/Actions/Entry/Timestamps.hs
- The default keybindings: https://github.com/NorfairKing/smos/blob/master/smos/src/Smos/Default.hs

**Comment by benjamin-macadam** [comment]
Hi, is it OK if I try working on this issue? It's an interesting looking project.

**Comment by NorfairKing** [comment]
@benjamin-macadam Go for it! No need to ask either :D

**Comment by benjamin-macadam** [comment]
@NorfairKing Sorry I haven't made more progress on this! Can you give me an intuition for how Timestamps work? I can't quite figure out how they're being stored in the state of the program.

**Comment by NorfairKing** [comment]
Hi @benjamin-macadam The links I gave in the issue are the pointers to the code.

Timestamps are in the editor cursor somewhere as a mapcursor of timestamps.
You can learn more about cursors here: https://smos.cs-syd.eu/blogposts
So to make these new actions, we need to add a way of transforming a timestampscursor to delete a timestamp, and then add a key binding for it.
Does that make sense? If you have any specific questions, feel free to ping me!

**Comment by benjamin-macadam** [comment]
@NorfairKing Thanks for this - I didn't quite understand how your cursor library worked (particularly the map cursor type). I've written a few utility functions for cursors that seem to solve the problem - would you be opposed to accepting a pull request on that library?

I'm not sure if you are aware of Connor McBride's paper on the [derivatives of regular datatypes](http://strictlypositive.org/diff.pdf), but from what I can tell your type:

``` haskell
newtype MapCursor kc vc k v
  = MapCursor
      { mapCursorList :: NonEmptyCursor (KeyValueCursor kc vc k v) (k, v)
      }
```

can be derived from the chain rule for derivatives from

```haskell
[(k,v)]
``` 

 where the type:

```haskell
data KeyValueCursor kc vc k v
  = KeyValueCursorKey kc v
  | KeyValueCursorValue k vc
  deriving (Show, Eq, Generic)
```

is the Liebniz rule for derivatives:

```
D[f*g] = D[f]*g + f*D[g]
``` 

and the derivative of a list is given by the zipper:

```haskell
newType Zipper a = Zipper [a] a [a]
```

**Comment by NorfairKing** [comment]
> I've written a few utility functions for cursors that seem to solve the problem - would you be opposed to accepting a pull request on that library?

I'd have to see the PR of course, but I'm definitely not opposed to contributions.

> can be derived from the chain rule for derivatives, 

I'm not sure what that means in practice, _at all_ :P

**Comment by benjamin-macadam** [comment]
Yes, so it seems like your cursor correspond to "one-hole-contexts" for a regular datatype, which is a generalization of Huet's zipper construction for lists. McBride showed, somewhat surprisingly, this construction satisfies a sort of chain rule when you compose regular datatypes together, so for example:

```haskell
D( [(Text, Timestamp)]) 
= ([(Text,Timestamp)], D (Text,Timestamp), [(Text,Timestamp)])
= ([(Text,Timestamp)], ( (Text, D (Timestamp)) + (D (Text), Timestamp)), [(Text,TimeStamp)]
= ([(Text,Timestamp)], KeyValueCursor TextCursor TimestampCursor Text TimeStamp, [(Text,Timestamp)])
= MapCursor TextCursor TimestampCursor Text TimeStamp
```
It's very cool you landed at the same type!

**Comment by NorfairKing** [comment]
Oh wauw, that is cool!
