### ISSUE TITLE
Commands and keybinding documention

### ISSUE THREAD

**Issue by anthrolisp** [NorfairKing/smos#16]
I've installed smos and can open it. I just don't know what to do from here. I'm an org-mode user and interested in learning more about how to use smos. Is there a list of default commands and keybindings? Many thanks in advance.

**Comment by NorfairKing** [comment]
Hey! Great question.

In every situation you can either use the keybinding `?` or `M-?` to go to the help menu to get an overview of the keybindings that you can use in your current situation.

I guess we should add this to the docs.
Really, we want separate pages that describe what kind of things are possible at all, but directing people toward using `?` would already help.
Do you want to make a PR and do that?

**Comment by NorfairKing** [comment]
@anthrolisp There is now a little message about this.
![empty](https://user-images.githubusercontent.com/3521180/71322615-efe4d800-24c9-11ea-925c-277393804674.png)

**Comment by NorfairKing** [comment]
Now there is also a nice documentation page about this: https://smos.cs-syd.eu/keybindings
