### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#160]
The current logo was donated last year during zurihack.
It's allowed by the license, but it's probably a better idea not to use the org-mode logo in the smos logo.

Smos is the dutch word for a very specific sandwhich that is common in Belgium:

![image](https://user-images.githubusercontent.com/3521180/94408286-de291300-0174-11eb-91c8-d909e8441c21.png)

You cannot eat this sandwhich without a mess, so I found it fitting as the name for an organisation tool.

I know nothing about making things pretty, so it would be great if someone who does would help out here.

**Comment by chamiduu** [comment]
Can you assign me to this? In my opinion, the current logo is too much complex. I can make a simple PixelArt logo.

**Comment by NorfairKing** [comment]
@chamindujs Go for it! Please let me know if I can help!

**Comment by lakshya-dhariwal** [comment]
Hey is it still available as the assingment was 2 days ago and there is no pull request. I can help

**Comment by NorfairKing** [comment]
@chamindujs ^

**Comment by bcksenanayake** [comment]
I created a new logo and I will make a PR.

**Comment by bcksenanayake** [comment]
Hey @NorfairKing can you review my PR?
