### ISSUE TITLE
"Server disconnected, refreshing in 2 seconds." repeatedly

### ISSUE THREAD

**Issue by Coda-Coda** [NorfairKing/smos#165]
After signing up and being redirected to https://smos.online/file/example.smos? I intermittently get the problem of `"Server disconnected, refreshing in 2 seconds."` and the page reloading repeatedly.

This is from Firefox 81.01 and macOS Catalina.

**Comment by NorfairKing** [comment]
@Coda-Coda I've heard about this before but I still haven't been able to reproduce this problem locally.
Does it happen immediately every time, or just sometimes?
Does it happen while you resize, or just while nothing is going on? 
Does it happen while typing or during 'silence'?

**Comment by NorfairKing** [comment]
I think I'll have to make re-usable smos sessions so if there's any network trouble, the session can be re-established.
If any hacktoberfest people with javascript/network/conduit experience have any ideas or want to join, please let me know!

**Comment by Coda-Coda** [comment]
Thanks for the reply.
>Does it happen immediately every time, or just sometimes?

It's intermittent, happening somewhere around 50% of the time, at least. Hard to say exactly.

> Does it happen while you resize, or just while nothing is going on?

With nothing going on, for instance now I opened it in a new tab from the link in this issue above and it repeatedly refreshed with that same error message. Refreshing the page manually did not help (though sometimes it has helped).

> Does it happen while typing or during 'silence'?

During 'silence', before any typing on the page has occurred.

**Comment by NorfairKing** [comment]
> before any typing on the page has occurred.

Aha! Does it also happen _after_ any typing has happened? Maybe there's something wrong with the initial resizing logic...

**Comment by Coda-Coda** [comment]
It typically occurs before typing has happened and then repeatedly so much so that it is not possible to type anything before it refreshes. Just now it loaded long enough for me to type `?` (and see the result), after which it crashed (reloading as before). So it seems to also sometimes occur after some typing has happened.

**Comment by NorfairKing** [comment]
@Coda-Coda Ok that's already helpful because it means the problem is probably related to resizing! If you happen to know something about Javascript or Websockets or Conduit, I'd be very happy with some help on this topic because I cannot seem to figure out why this happens..

**Comment by Coda-Coda** [comment]
Sorry I can't offer help at this stage, I think you are probably right about the (automatic) resizing being involved. Here's the console log that appears (then repeatedly disappears and reappears) during the issue:

```
Some cookies are misusing the recommended “SameSite“ attribute 3
trying to resize. example.smos:84:11
Resizing immediately example.smos:106:13
Actually resizing. example.smos:64:11
Disconnected: example.smos:127:13
close { target: WebSocket, isTrusted: true, wasClean: false, code: 1006, reason: "", srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, … }
example.smos:128:13
```

**Comment by NorfairKing** [comment]
Thanks! That _really_ helps. I'll have a closer look.-

If only there was a way to write an integration for this...

**Comment by NorfairKing** [comment]
@Coda-Coda I think this should have been fixed by now. Have you seen it since?

**Comment by Coda-Coda** [comment]
Hi, I've tried on two occasions and haven't experienced any issues anymore myself 🙂
I have actually switched to LInux since I experienced the issues so it is remotely possible that the issue was Mac specific but I doubt it - I'm going to assume it is fixed and close the issue. Thanks @NorfairKing!
