### ISSUE TITLE
q not working with "Next action report"

### ISSUE THREAD

**Issue by llattila** [NorfairKing/smos#169]
When the user uses "rn" and goes to the "Next action report", the user can't quit smos with "q". The user has to select a task or use browse actions to be able to quit smos.

**Comment by NorfairKing** [comment]
@llattila I was just able to reproduce this.
This is because when you press `q`, smos tries to go back to the file editor.
If you've never opened a file in the session, then it will just do nothing.
I'm not sure what to do here. Should we change it so that `q` always quits, or do something fancier?

**Comment by llattila** [comment]
Perhaps if no file in session, go to the workflow?

**Comment by NorfairKing** [comment]
Yes, I think we'll need an `exitReport` action.

**Comment by ketzacoatl** [comment]
@norfairking, can you point to (roughly) where in the codebase this would be setup, and/or another action that is similar in structure/function?

**Comment by NorfairKing** [comment]
@ketzacoatl  LIke for the help screen we have `exitHelp` https://github.com/NorfairKing/smos/blob/master/smos/src/Smos/Default.hs#L350-L354, we'll want to make an `exitReport`.

**Comment by ketzacoatl** [comment]
@norfairking, to confirm.. we want to hit q and exit smos from within the next action report, do I understand correctly?

There is an existing `quit` `Action`, should that be used/mapped to `q` like:

```
      nextActionReportAnyMatchers =
        listMatchers
          [ exactChar 'q' quit ]
```

Or should this be hooked up differently? LMK, thanks!

**Comment by NorfairKing** [comment]
> @NorfairKing, to confirm.. we want to hit q and exit smos from within the next action report, do I understand correctly?

If there is a file open, go to it (this already works).
If there is no file open, go to the browser in the `workflow` dir.

What you suggest is already better than what we have now, but not ideal.
This will take a custom `exitReport` action I think.
You can take inspiration from the `exitHelp` action.

**Comment by ketzacoatl** [comment]
Hello @NorfairKing,

> This will take a custom `exitReport` action I think.
> You can take inspiration from the `exitHelp` action.

I have a WIP I've wired up, but I have had a difficult time figuring out what the inner function of the action should actually do (I'm not familiar with what's there and what this should do). Looking at `exitHelp` is helpful for this, but also confusing. For example, do I need to use a case on `editorCursorSelection`? If so, what's used instead of `HelpSelect`?

Here is my WIP: https://github.com/NorfairKing/smos/compare/development...ketzacoatl:wip-exit-next-action-report?expand=1#diff-0f2f559e80343ca0d60ccb8118be732790dd30467a125c9bbd80c0ff7a50edbdR155-R166

**Comment by NorfairKing** [comment]
@ketzacoatl Let's start a PR so that we can iterate from there.
The `Selection` is about which part of the selection is currently being looked at.

**Comment by ketzacoatl** [comment]
> Let's start a PR so that we can iterate from there.

OK, I've added #179.

>  The Selection is about which part of the selection is currently being looked at.

If I understand correctly, we won't need that for this Action to exit the Next Action Report.

**Comment by NorfairKing** [comment]
> If I understand correctly, we won't need that for this Action to exit the Next Action Report.

Yes that sounds right!

**Comment by ketzacoatl** [comment]
Thanks @NorfairKing, I have updated my PR and it's ready for another review.

If my existing update works for you, I'd prefer to merge and make new PRs for additional changes, but LMK if you see changes you would like me to make before merging.

**Comment by NorfairKing** [comment]
Fixed, thanks @ketzacoatl !
