### ISSUE TITLE
Provide a Docker image

### ISSUE THREAD

**Issue by ad-si** [NorfairKing/smos#177]
This would be the easiest way to try out smos, without having to install anything.
E.g. I often use Taskwarrior like this:

```sh
docker run --rm -it \
             -v $HOME/.taskrc:/root/.taskrc \
             -v $HOME/.task:/root/.task \
             jamesnetherton/taskwarrior
```

**Comment by NorfairKing** [comment]
So I just tried this using `dockerTools` but it made a 5GiB image. I tried again using the static build and that gave a 1GiB image for unknown reasons.

**Comment by NorfairKing** [comment]
Feel free to try it as well!

**Comment by dotcs** [comment]
@NorfairKing I'd like to help with this. Can you describe the commands you tried? Or even better point to the Dockerfiles that you have used. I'm pretty sure that a Docker image of ~100MB size should be possible.

**Comment by NorfairKing** [comment]
@dotcs

`dockerTools` is a way to make docker images from nix. It skips the `Dockerfile` step.
But if you have access to Nix then you might as well just use Nix to build smos.
I don't use docker myself, so if you get something working then we'd have to discuss how to keep it working.

**Comment by NorfairKing** [comment]
Pr still welcome :)

**Comment by prikhi** [comment]
I got a little thing going that builds w/ nix, long term plan of running a sync server on a cheap VM:

```Dockerfile
#syntax=docker/dockerfile:1

FROM nixos/nix:2.18.1

ARG PORT=7788
ARG LOG_LEVEL=Debug

RUN nix-channel --update

RUN git clone https://github.com/NorfairKing/smos.git /build

WORKDIR /build
RUN nix --extra-experimental-features nix-command --extra-experimental-features flakes --accept-flake-config build .
RUN mv ./result/bin/* /usr/bin/

WORKDIR /app
EXPOSE $PORT
ENV SMOS_SERVER_PORT=${PORT}
ENV SMOS_SERVER_LOG_LEVEL=${LOG_LEVEL}
ENTRYPOINT [ "/usr/bin/smos-server" ]

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD [ "curl localhost:${PORT}/api-version" ]
```

```sh
docker build . -t smos:latest
docker run -p 7788:7788 smos:latest
```
```
$ curl http://localhost:7788/api-version 2> /dev/null | jq -r
0.4.0
```

I have some github actions for another project that show how to build & push images to dockerhub:
https://github.com/prikhi/sleepanarchy/blob/master/.github/workflows/main.yml#L172
But I noticed GH actions were killed a bit ago?
