### ISSUE TITLE
Append / Insert in browse mode

### ISSUE THREAD

**Issue by llattila** [NorfairKing/smos#180]
Currently if the user makes a typo when creating a new smos file in the browse mode, there are no ways to modify the file name. It would be good to have the insert and append operations available in the browse mode as it would much easier to modify the name there than go to the actual file.

**Comment by NorfairKing** [comment]
I agree, this is a great idea! 

However, it's quite complex to actually do because the cursor and the filesystem have to stay in sync.
If you're interested in building this then I'd be happy to review and help.
