### ISSUE TITLE
Flaky tests in smos-web-server

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#183]
When running the `smos-web-server-test`, I get a test failure about every 100-1000 runs.
![flaky](https://user-images.githubusercontent.com/3521180/102829113-aeda1900-43e6-11eb-9a5e-cc069a48b89c.png)

To reproduce, run `stack test :smos-web-server-test --ta='--continuous'`.

**Comment by NorfairKing** [comment]
I don't think it's from `entropy` because they use `/dev/urandom`, not `/dev/random`: http://hackage.haskell.org/package/entropy-0.4.1.6/docs/src/System.EntropyNix.html#source

**Comment by NorfairKing** [comment]
I don't think quickcheck would use /dev/random because quickcheck is all about deterministic randomness... (and I only use fixed seeds)

**Comment by NorfairKing** [comment]
Moreover, It looks like `splitmix` (so `QuickCheck`) doesn't use `/dev/random` either, but the system CPU time: https://hackage.haskell.org/package/splitmix-0.1.0.3/docs/src/System.Random.SplitMix.Init.html#initialSeed

**Comment by andrewthad** [comment]
Possibly `yesod-auth`:

```
amartin@mycomputer:~/Development/yesod-auth-1.6.10.1$ ag 'dev.random'
Yesod/Auth/Util/PasswordStore.hs
210:    Control.Exception.catch genSaltDevURandom def
216:genSaltDevURandom :: IO Salt
217:genSaltDevURandom = withFile "/dev/urandom" ReadMode $ \h -> do
```

`withFile` will attempt to close the file at the end. Although this is `urandom` and not `random`.

**Comment by NorfairKing** [comment]
I just found out something else
sydtest is doing multiple iterations of the test suite
and after about 1200 iterations it runs into this error (if it doesn't run into the other one):

```
openBinaryFile: resource exhausted (Too many open files) @(yesod-core-1.6.18-HPWjDsCk5dC5G5qOS7HMIN:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:688:5)
```

so then i added performGC after every iteration of the test suite and now that problem is gone

**Comment by NorfairKing** [comment]
I can't seem to reproduce this problem anymore :( 
I thought https://github.com/NorfairKing/sydtest/commit/8dc38b3e495ff9e333453ad9183f6ed37fef197c would have fixed it (smos version 47ad5de6) but I can't even reproduce the problem with the version of sydtest before that commit (smos version 553f0c23).

**Comment by NorfairKing** [comment]
I've now run 5000 iterations of this test suite and cannot reproduce the problem anymore...

**Comment by goertzenator** [comment]
I got this exact same error just now on an embedded web app that I am working on.  I'm curious if you've learned anything more about this since you closed it.

**Comment by NorfairKing** [comment]
@goertzenator I've seen this problem again in many places but haven't investigated further. I'm guessing there's a race condition in `withFile`.

**Comment by ketzacoatl** [comment]
@NorfairKing `withFile` from `System.IO` in `base` - https://www.stackage.org/haddock/lts-18.3/base-4.14.1.0/System-IO.html#v:withFile?

**Comment by NorfairKing** [comment]
@ketzacoatl yes that's right.

**Comment by ghost** [comment]
@NorfairKing which Linux distro (and version) was used during tests?

**Comment by NorfairKing** [comment]
> @NorfairKing which Linux distro (and version) was used during tests?

NixOS, but all the versions are pinned in the `shell.nix`.
