### ISSUE TITLE
Smos-scheduler time-library format string in documentation

### ISSUE THREAD

**Issue by llattila** [NorfairKing/smos#186]
The `smos-scheduler` has a rather vague information in regards of time-library format string. The documentation should be extended to include more information on these so the user would be more familiar with their usage

**Comment by NorfairKing** [comment]
Yes, let's point it to https://hackage.haskell.org/package/time-1.11.1.1/docs/Data-Time-Format.html#v:formatTime

**Comment by ketzacoatl** [comment]
@NorfairKing maybe you can point me in the right direction here? Where should this be added?

**Comment by NorfairKing** [comment]
@ketzacoatl Here: https://github.com/NorfairKing/smos/blob/master/smos-docs-site/content/pages/smos-scheduler.markdown
