### ISSUE TITLE
Support Flakes

### ISSUE THREAD

**Issue by a-kenji** [NorfairKing/smos#187]
Hello! 
I think it would be great to start transitioning into
supporting Flakes.
Sadly I don't know much about the
Haskell Infrastructure in Nix and how feasible that is,
especially with some dependencies.

**Comment by NorfairKing** [comment]
I'm not opposed to this, but I haven't done it because I haven't used flakes yet.
I haven't used flakes yet because they're an experimental feature (at the time of writing this).
If you're interested in having flakes supported, it would be great if you could figure out what is necessary to do that.

**Comment by a-kenji** [comment]
Yes, I will look into it.
In a broad sense the evaluation of functions like
```
builtins.currentSystem,
builtins.storePath,
...
```
can't be evaluated inside of a flake.
I will try to figure out where they are called.

**Comment by contrun** [comment]
@a-kenji Any progress on this?

**Comment by a-kenji** [comment]
@contrun, no sadly not.
IIRC I think some of the libraries that were/are used to manage dependencies with haskell/nix
generate some of the code that is incompatible with pure flakes. I didn't make any more progress than that
and I don't plan on going that route in the near future. Though that doesn't mean that I won't look at it
further down the line.

I should have said so sooner.

**Comment by NorfairKing** [comment]
This is done in #250

**Comment by a-kenji** [comment]
Thank you! It works well.
