### ISSUE TITLE
Installing binaries in user environment with nix fails with "packages (...smos-report...) and (...smos-shell...) have the same priority 5; use (...)" (macOS)

### ISSUE THREAD

**Issue by mputz86** [NorfairKing/smos#188]
Maybe that is an issue of my incompetency with nix, so maybe a hint in the installation instructions is useful.

I try to install with nix, so
```bash
nix-build
nix-env -if default.nix
```

But this fails with a "packages (...smos-report...) and (...smos-shell...) have the same priority 5; use (...)". Full trace:
```
nix-env -if default.nix
installing 'smos-0.1.3'
installing 'smos-api-0.1.0'
installing 'smos-api-gen-0.1.0'
installing 'smos-archive-0.2.0'
installing 'smos-calendar-import-0.2.0'
installing 'smos-client-0.1.0'
installing 'smos-client-gen-0.1.0'
installing 'smos-cursor-0.2.0'
installing 'smos-cursor-gen-0.1.0'
installing 'smos-data-0.1.0'
installing 'smos-data-gen-0.1.0'
installing 'smos-query-0.2.1'
installing 'smos-report-0.2.0'
installing 'smos-report-cursor-0.1.0'
installing 'smos-report-cursor-gen-0.1.0'
installing 'smos-report-gen-0.1.0'
installing 'smos-scheduler-0.1.0'
installing 'smos-server-0.1.0'
installing 'smos-server-gen-0.1.0'
installing 'smos-shell-0.0.0.0'
installing 'smos-single-0.1.0'
installing 'smos-sync-client-0.1.0'
installing 'smos-web-server-0.1.1'
building '/nix/store/vq16wy2qhimprg4a179fk2xljy4zzmyk-user-environment.drv'...
error: packages '/nix/store/2zqi6zlailk4s2nfig0pyrk17cwr3nc6-smos-report-gen-0.1.0/lib/links/libgmpxx.4.dylib' and '/nix/store/1qi0bblv7jf2zc1nphn91a32bjs7amgc-smos-shell-0.0.0.0/lib/links/libgmpxx.4.dylib' have the same priority 5; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
builder for '/nix/store/vq16wy2qhimprg4a179fk2xljy4zzmyk-user-environment.drv' failed with exit code 1
error: build of '/nix/store/vq16wy2qhimprg4a179fk2xljy4zzmyk-user-environment.drv' failed
```

When I install the required binaries in sequence and set the priority flag along the way, it works for a subset of all binaries:
```bash
nix-env -if default.nix -A smos
nix-env --set-flag priority 3 smos-0.1.3
nix-env -if default.nix -A smos-query
nix-env --set-flag priority 4 smos-query-0.2.1

nix-env -if default.nix\
  -A smos-archive\
  -A smos-single\
  -A smos-sync-client
```

But I highly assume, I am doing something wrong.
I am on macOS.

**Comment by NorfairKing** [comment]
@mputz86 thanks for the report.

(0. This is not _your_ fault!)
1. I have no idea what is happening with those priorities.
2. I probably shouldn't be recommending the `nix-env -if` way of installing things.
3. Some packages cannot be built on macos, and I can't fix this because I don't have any apple device so I can't investigate. But this doesn't seem to be what's at play here.

Proposed fix:

1. Update the install instructions to not recommend the `nix-env -i` method.
2. Optional: fix this priorities problem?

@domenkozar, can you explain what's going on here?

**Comment by mputz86** [comment]
@NorfairKing Thanks for the fast reply :) . Just some remarks with low additional content level :D .
- At least for me, all packages and binaries built
- (Besides the issue, I prefer this way of installation 😂  )
- It seems that this `lib/links/libgmpxx.4.dylib` is in both mentioned packages (smos-report-gen and smos-shell) and the user-environment-installation does not know which one to choose 🤔 , whatever this means 🤷‍♂️ 
- Which confuses me on how this is done in 'non-macos-envs' (totally wild assumption: nix realizes that both libs are 100% equal and picks randomly 🤷‍♂️ )

**Comment by domenkozar** [comment]
@NorfairKing if you have packages install the same files, you need to define priorities (which files will then be "the one" in side the profile). 

I'd recommend to install only packages that are really needed with just executables.

**Comment by NorfairKing** [comment]
I have no clue why these packages would install the same files. Is that a mac thing?

**Comment by domenkozar** [comment]
It's macOS specific (hack) that prevents hitting max length error with dynamic libraries.

**Comment by NorfairKing** [comment]
Aha, in that case I actually can't do anything because I don't own any apple devices.

**Comment by domenkozar** [comment]
You could test that on github actions (and use something like
https://github.com/luchihoratiu/debug-via-ssh to debug it)
