### ISSUE TITLE
Incorrect alignment when contents include CJK characters

### ISSUE THREAD

**Issue by Ninlives** [NorfairKing/smos#190]
CJK characters usually occupy twice the width of ordinary characters, but smos seems to be unable to handle this situation, so when the content contains some CJK characters, the alignment is strange.

![image](https://user-images.githubusercontent.com/17873203/107884004-5ed28b00-6f2d-11eb-922b-302e40072a2f.png)

**Comment by NorfairKing** [comment]
I'm so excited that my efforts to make sure that these characters are considered valid and are rendered at all were not in vain :D :D

Ok:

1. I can't read or write these characters and I don't know what they mean, so I will need help with navigating this complexity.
2. I'm using `Rainbox`, which uses `Text.length` to determine the width of a box https://github.com/massysett/rainbox/blob/3e442b10f27a366b1b2ec8800b2f9dfcbf31e66d/lib/Rainbox/Core.hs#L119 cc @massysett Is that not the right way to determine the width of a text? If so, what would be the standard way to solve this problem?

**Comment by NorfairKing** [comment]
Another question: Does this work when you run an interactive report? Try pressing `rn` inside smos and see if it renders right please.

**Comment by Ninlives** [comment]
> Another question: Does this work when you run an interactive report? Try pressing `rn` inside smos and see if it renders right please.

It works perfectly in an interactive report:

![image](https://user-images.githubusercontent.com/17873203/107908616-6c216100-6f91-11eb-8a7a-f08e22fa08cd.png)

**Comment by NorfairKing** [comment]
> It works perfectly in an interactive report:

@jtdaugherty That's your doing. Great job! :D

Would you mind explaining how you get these character widths right, because `Data.Text.length` doesn't seem to.

**Comment by NorfairKing** [comment]
@jtdaugherty I just found this:
https://github.com/jtdaugherty/vty/blob/master/cbits/mk_wcwidth.c

Oh dear oh dear, this looks to be quite the rabit hole.

**Comment by jtdaugherty** [comment]
@NorfairKing This is a messy issue, but for now the best you can do is to use the functions from [this module](http://hackage.haskell.org/package/vty-5.32/docs/Graphics-Text-Width.html). There are caveats to this, though; Vty will get some widths wrong, and even when it *doesn't*, the terminal emulator needs to agree with those widths, and that will vary by terminal emulator.

**Comment by jtdaugherty** [comment]
(To put it another way: *never* use `Data.Text.length` for this.)

**Comment by jtdaugherty** [comment]
If you're interested, I can link to various spots where I've discussed the finer details of why this is such a mess, but for now, another thing to know is that Vty's width computation does no lookahead, so it doesn't support zero-width joiner characters. That means it will be especially wrong for any Unicode character that is itself a combination of other characters.

**Comment by jtdaugherty** [comment]
Another thing that might be helpful: Vty supports *custom character width tables* that can help Vty get more widths right for a given terminal emulator. For details on how to take advantage of that, see

https://github.com/jtdaugherty/vty#multi-column-character-support

**Comment by NorfairKing** [comment]
@jtdaugherty thanks for the pointers! I won't be able to be fix this soon unless I can get @massysett to fix this in `Rainbox` (or fork/write my own `RainBox`). But now at least we know where to look :)

**Comment by NorfairKing** [comment]
So I did end up writing a `RainBox` replacement: https://github.com/NorfairKing/safe-coloured-text/tree/master/safe-coloured-text-layout We can follow up there.

**Comment by NorfairKing** [comment]
This is now an issue for `safe-coloured-text-layout`.
