### ISSUE TITLE
Show context in the report

### ISSUE THREAD

**Issue by Ninlives** [NorfairKing/smos#192]
I usually have many similar subtask for different tasks, for example I have to do presentations for different project.
Then in the work report or agenda, there will be two entry named "Presentation", but what I want is to show something like "ProjectA/Presentation", "ProjectB/Presentation". Can I archieve this in the current release version?

**Comment by NorfairKing** [comment]
@Ninlives The filepath is shown in both reports. It's good practice to have projects be as small as possible, and use directories to group projects.
Does this solve your problem?

**Comment by Ninlives** [comment]
Well..I still want to have a way to control how things are displayed, but it looks like it's not on the roadmap?

**Comment by NorfairKing** [comment]
In the work report you can control which columns are displayed but now how.
Could you show me a diff between what you're seeing and what you'd like to see?

**Comment by Ninlives** [comment]
For example I may have such content in my smos database:
![image](https://user-images.githubusercontent.com/17873203/110960347-9cd69980-8389-11eb-865d-153d8df0bbe7.png)
Currently the work report displays like this:
![image](https://user-images.githubusercontent.com/17873203/110960497-c8f21a80-8389-11eb-86e9-fb9d87a2d20d.png)
And I want something like:
```
example.smos                NEXT    Task1/Presentation                                 
example.smos                NEXT    Task2/Presentation  
```
Is this doable in the current version?

**Comment by NorfairKing** [comment]
@Ninlives It's not, in the current version. You'd have to make multiple files (projects) for that currently.

Like this:

```
task1.smos                NEXT    Presentation                                 
task2.smos                NEXT    Presentation  
```
 I'm not necessarily opposed to this, by the way. We'd just have to add a projection here: https://github.com/NorfairKing/smos/blob/master/smos-report/src/Smos/Report/Projection.hs#L28

**Comment by NorfairKing** [comment]
PR welcome
