### ISSUE TITLE
No complaints in smos work report from faulty timewindow formats

### ISSUE THREAD

**Issue by llattila** [NorfairKing/smos#193]
Would be great if smos would complaint about faulty timewindows. Noticed in my weekly that some tasks had `15min` and not `15m`, so they didn't show in the work report.

**Comment by NorfairKing** [comment]
@llattila I agree. This should be doable. Also it would be nice if `15min` would also "just work". You can fix it here as well https://github.com/NorfairKing/smos/blob/master/smos-report/src/Smos/Report/Time.hs#L63

**Comment by ketzacoatl** [comment]
@llattila / @NorfairKing, I've added a simple first-pass at that, as suggested above. LMK what you think about that, if it should be updated or done differently.

**Comment by NorfairKing** [comment]
@llattila While this issue is still valid, `15min` is now also recognised as a timewindow.

**Comment by ketzacoatl** [comment]
@NorfairKing With the `m`, `mins`, `min`, `minute`, and `minutes` being acceptable and parsing to `Minutes`, how would smos differentiate (maybe a spelling mistake? `mniute`), and identify a faulty timewindow from other words or intentions the user had?

**Comment by NorfairKing** [comment]
@ketzacoatl it still doesn't, that's why this issue is still open :D

**Comment by NorfairKing** [comment]
I must have closed this accidentally.

**Comment by NorfairKing** [comment]
PR still welcome
