### ISSUE TITLE
Add command to `smos-scheduler` to print next scheduled runs

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#194]
When creating new recurring projects that are to be run with `smos-scheduler` it is helpful to run the `check` command but I frequently find myself changing the schedule to try to find an optimal day/time for me to do a particular recurring task and this means that I can mess up my schedule. This is a feature request to add a `next` command to `smos-scheduler` that would print out the next iteration for each project, similar to how the `schedule` command prints a sort of status next to each scheduled project.

**Comment by ketzacoatl** [comment]
@distefam That sounds useful, but I'm not sure I follow your description. Maybe you can scope out an example for what that would look like when called? eg the params passed and the output from `smos-scheduler`. That would help make it more obvious. I would be happy to help with implementation, but need more clear requirements to be effective :)

**Comment by NorfairKing** [comment]
@ketzacoatl It's just the output of https://github.com/NorfairKing/smos/blob/83b5bd3f9b39fb5560edfc5656d49bbe7e79bada/smos-scheduler/src/Smos/Scheduler/Commands/Schedule.hs#L86 :D

**Comment by ketzacoatl** [comment]
OK, so `smos-schedule next` should effectively call `calculateScheduledTime` and that's it?

**Comment by NorfairKing** [comment]
@ketzacoatl Jup!

**Comment by ketzacoatl** [comment]
OK, I'll take a crack at it.

**Comment by ketzacoatl** [comment]
I haven't lost track of this, will hopefully have something this week.

**Comment by ketzacoatl** [comment]
@NorfariKing, When running an initial build of `smos-scheduler`, I am running into this error about a missing CSS asset:

```
smos-web-style                  > WARNING: Including style files from dir at path:  /src/smos/smos-web-style/style/
smos-web-style                  > Regenerating the stylesheet at /src/smos/smos-web-style/style/mybulma.css  
smos-web-style                  > Error: File to import not found or unreadable: bulma/bulma.sass.                     
smos-web-style                  >         on line 34 of /src/smos/smos-web-style/style/mybulma.scss          
smos-web-style                  >   Use --trace for backtrace.                                                         
smos-web-style                  > Regenerating the stylesheet failed with exit code: 65                                
smos-web-style                  >                                                                                      
smos-web-style                  > /src/smos/smos-web-style/src/Smos/Web/Style.hs:1:1: error:                 
smos-web-style                  >     Exception when trying to run compile-time code:                                  
smos-web-style                  >       ExitFailure 1                                                                  
smos-web-style                  >     Code: mkStyle                                                                    
smos-web-style                  >   |                                                                                  
smos-web-style                  > 1 | {-# LANGUAGE TemplateHaskell #-}                                                 
smos-web-style                  >   | ^                                                                                
smos-web-style                  >   
```

Am I doing something wrong in the build, or is something else off? This is on `development`.

**Comment by NorfairKing** [comment]
```
smos-web-style                  > WARNING: Including style files from dir at path:  /src/smos/smos-web-style/style/
smos-web-style                  > Regenerating the stylesheet at /src/smos/smos-web-style/style/mybulma.css  
smos-web-style                  > Error: File to import not found or unreadable: bulma/bulma.sass.    
```

Did you `git clone --recursive`?
You can run `git submodule update --init --recursive` now if you didn't.
We should add this to the contributing docs.

**Comment by NorfairKing** [comment]
> We should add this to the contributing docs.

I'm doing this right now :D

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/smos/commit/c7876401cba6e0f9ec3b931172bb35144a35740b @ketzacoatl Have a look at this :)

**Comment by ketzacoatl** [comment]
I figured out a few of those piecemeal, so that looks super to me! I did need the submodule update, thank you.

**Comment by NorfairKing** [comment]
![next](https://user-images.githubusercontent.com/3521180/120860796-8a35c000-c586-11eb-844d-6a2e2dcf77d7.png)
I took a stab at this.

**Comment by NorfairKing** [comment]
Now on development: https://github.com/NorfairKing/smos/commit/596cfffb7edb03a3c4e91d384c7be54cdb80f4cb

Closing this, feel free to reopen if this command doesn't do what you wanted and we can discuss.
