### ISSUE TITLE
Add a meta tag for non-obsolete entries

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#197]
Frequently when using `smos-query` I want to filter for all entries that are "available", which simply means anything that is not CANCELLED, DONE, or FAILED. This suggestion is to add a "meta-tag" in that the state itself will not exist but be a pre-defined filter to show only those that are available.

**Comment by NorfairKing** [comment]
You can do this using the `not:state:(CANCELLED or (DONE or FAILED))`. Does this filter solve your problem?

**Comment by distefam** [comment]
That is what I am currently doing, however, it is cumbersome to type out every time. I was basically hoping for an alias for that.

**Comment by NorfairKing** [comment]
@distefam You can use prepared reports https://docs.smos.online/smos-query/report to define your own alias. (or just shell aliases of course)

**Comment by NorfairKing** [comment]
@distefam does that solve your problem?

**Comment by distefam** [comment]
Not really in that it does not solve the problem for writing ad-hoc queries from the command-line. For example, I might have entries with a tag of `wife` that have one of the following states that are all "in play": `waiting`, `todo`, `next`, `ready`. When I'm talking with my wife I don't necessarily only want to do `next` items as I can usually knock out a few `todo` items while addressing some I might be `waiting` for also. So, I could write this like `smos-query entry tag:wife not:state:(FAILED or DONE or CANCELLED)` but this would be much nicer to write like `smos-query entry tag:wife state:ACTIVE`
