### ISSUE TITLE
Add ability to remove scheduled and due timestamps from entry

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#198]
Frequently, I will set a scheduled timestamp and wish to remove it later. Often, this is simply because my muscle-memory malfunctioned and I set a timestamp unintentionally. Other times, I wish to remove a timestamp that was set that is no longer relevant. Either way, it is not possible to do this in smos directly but I must edit the YAML files instead. Even undo cannot remove a timestamp if I have just set one.

**Comment by NorfairKing** [comment]
This is on development since d99ded54fc8d2c8ead9c0d2accd29300197190fc
