### ISSUE TITLE
Add fuzzy filter within a smos file

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#199]
Most of my smos files are quite small. However, my "someday/maybe" file has many lines. I use `grep` within another terminal window to find things, which reports with a line number, however, that isn't really helpful when I'm looking for something. It would be great to be able to fuzzy filter within a file like what is possible within the project browser. 

Otherwise, some command to go to a specific line number would be helpful.

**Comment by distefam** [comment]
Encountering the problem for which this solution was proposed could be solved by #215

**Comment by NorfairKing** [comment]
PR welcome
