### ISSUE TITLE
Getting a DecodeFailure when running any smos-sync-client command

### ISSUE THREAD

**Issue by jhbertra** [NorfairKing/smos#200]
Installed `smos-sync-client` v0.1.2, attempted to run `smos-sync-client login`, here is the response:

```hs
DecodeFailure "not enough input" (Response {responseStatusCode = Status {statusCode = 204, statusMessage = "No Content"}, responseHeaders = fromList [("Server","nginx"),("Date","Wed, 28 Apr 2021 12:33:54 GMT"),("Content-Type","application/json;charset=utf-8"),("Connection","keep-alive"),("Set-Cookie","JWT-Cookie=<redacted>; Path=/; HttpOnly; Secure; SameSite=Lax")], responseHttpVersion = HTTP/1.1, responseBody = ""})
```

Also tried adding a plaintext password in the config file and running `sync`, same problem - HTTP response had no content.

**Comment by NorfairKing** [comment]
@jhbertra This is my fault I think.
The latest version of `master` corresponds to `staging.api.cs-syd.eu`
The release version on the `release` branch corresponds to `api.cs-syd.eu`.

I accidentally made the versions not backward-compatible by assuming that turning `GetNoContent` into `Get` would "just work".
I'll add some regression tests to make sure that this doesn't happen again.
In the meantime you can install the version on the `release` branch to interact with `api.smos.online`.

Please let me know if that doesn't do the trick.

**Comment by NorfairKing** [comment]
Update: made the `release` branch the default branch on github.

**Comment by NorfairKing** [comment]
Another update:
I've started work on some end-to-end testing that should consistently prevent problems like this in the future and it would be great if you could tell me whether this makes sense to you:

We write a binary called `smos-server-end-to-end-test` which runs a test suite against a remote api that you point it to (via an env var or so).
Then we run that test suite in multiple environments:

* On ci against the version currently in CI
* In testing against testing for current-compatibility in a real environment
* In staging against staging for current-compatibility in a real environment
* In testing against staging for backward compatibility
* in staging against testing for forward compatibility

Does this make sense?

**Comment by NorfairKing** [comment]
I just released a new version of smos, this should be fixed on the latest release now.

**Comment by NorfairKing** [comment]
Please reopen if it hasn't been fixed.

**Comment by jhbertra** [comment]
@NorfairKing pulled this morning and attempted to login - looks like this issue is fixed, thanks! Running into another one, I'll open a new issue if it hasn't been reported already.
