### ISSUE TITLE
Add alternating row color tables in interactive editor

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#204]
Alternating colors for rows in the interactive editor would be great. This works via the non-interactive `smos-query` commands.

**Comment by NorfairKing** [comment]
In `smos-query` we can do this because of `safe-coloured-text`, but in `smos` we'd have to do it with `brick` instead.
It should be possible with some clever uses of `vBox`.

**Comment by NorfairKing** [comment]
PR welcome
