### ISSUE TITLE
Add a column option for custom reports to display whether there is a note

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#211]
Just a boolean indication whether a given task contains a note or not would be nice to have as a column option for custom reports.

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/smos/blob/91efacaede3574e2f8f9d9601bf0383897eebfd8/smos-report/src/Smos/Report/Projection.hs#L26

This should be very doable. Just add another constructor here and follow the errors.

**Comment by NorfairKing** [comment]
PR welcome
