### ISSUE TITLE
Add ability to link to external note from entry

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#215]
Certain entries, meeting notes for example, require a bit more note-taking than smos is currently set up to do. Rather than adding more robust text editing functionality to smos it could be best to stick with the "unix philosophy" and use an external application for editing longer notes. For these somewhat rare scenarios it would be useful to link to an external notes file, which could simply be a regular `.txt, .org, .md` file. This file could then be opened in an external editor via `xdg-open` just as URLs are. 

How this could work:
- While on entry user presses `pn` keyboard command
- smos triggers configured `$EDITOR` to launch so user can input free-form note content
- smos saves note to filesystem and associates with entry somehow
- smos displays something beside the entry to indicate it has an external note
- user presses `<space>on` to open the note in the external `$EDITOR`

**Comment by distefam** [comment]
this is likely the main (only?) scenario in which #211 would be applicable.

**Comment by NorfairKing** [comment]
Yes I've thought about this for a while. The problem is when `EDITOR` is also a TUI. To make this work well, I need to refactor the entire action infrastructure to support that situation.

**Comment by NorfairKing** [comment]
Linking would break the semantic-ness of the semantic editor, but you can already open contents with `EDITOR`.
