### ISSUE TITLE
Add ability to extract subtree to new smos file

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#216]
It frequently occurs that I find myself with a project that has grown unexpectedly unweildy. These projects start small but organically grow to contain subtrees that should be their own projects. This proposal simply exports the subtree including the entry one is on to a new smos file.

**Comment by NorfairKing** [comment]
Also on my list, but it will require a bit of infrastructure because what would the new file be called?

**Comment by NorfairKing** [comment]
PR welcome
