### ISSUE TITLE
Make smos-notify ignore Google Calendar's out-of-office events

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#217]
Google Calendar has a special feature that allows you to mark events as "Out of Office". These events do not allow one to include a description, however, which means that I cannot use `NO_SMOS_NOTIFY`. Presumably, there is some way to tell that this event is an out of office event, however, and perhaps that could be used to tell `smos-notify` to ignore it.

Use case:
I create these special type of Google calendar events on my work calendar so that others don't schedule meetings when I have events on my personal calendar. I manually do this every week during my weekly review.

**Comment by NorfairKing** [comment]
> Presumably, there is some way to tell that this event is an out of office event, however, and perhaps that could be used to tell smos-notify to ignore it.

I don't know, is there? can you point to it in the ICS file?
