### ISSUE TITLE
Bug - Archiving file routes to projects instead of PWD

### ISSUE THREAD

**Issue by jhbertra** [NorfairKing/smos#218]
Steps to reproduce:

- Setup a workflow directory with at least a `projects` directory
- Create a new smos file in the *root directory* (`~/workflow/new-project.smos`)
- open the smos tui in the root directory (`~/workflow`)
- open `new-project.smos`
- Add an entry
- run `convArchiveFile` (`<space>fa`)

Expected final state:

- browser is in the `~/workflow` directory` (directory the archived file was in)

Actual final state:

- browser is in the `~/workflow/projects`

**Comment by jhbertra** [comment]
https://user-images.githubusercontent.com/1339296/122792295-09660c00-d288-11eb-9307-251647a4b0da.mp4

Here's a screen recording of the issue

**Comment by NorfairKing** [comment]
Aha! Good point, thanks for the detailed report.
This is quite low priority but I'd be happy with a PR!

**Comment by NorfairKing** [comment]
PR welcome
