### ISSUE TITLE
Remember folding when re-entering a smos file

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#219]
I frequently bounce between the interactive work report and a given smos file (via the work report). Every time I open a smos file from the work report it opens with every entry fully expanded. This is frustrating as I have several large smos projects where I've folded certain sections, mostly those that are complete or haven't yet begun.

**Comment by NorfairKing** [comment]
Yes I think we either need to do a big refactor to support a more general undo-stack, and/or fix the unfolding when you open a file.

**Comment by tusj** [comment]
Has this behavior changed? I am just getting started with smos, and I experience that smos opens the file with entries folded. Folding for time and content seem to be remembered though.

**Comment by NorfairKing** [comment]
@tusj Nothing has changed on this front in years. Smos unfolds according to this: https://github.com/NorfairKing/smos/blob/a3ed8fdbcb8f298bc49866bf6d0ee59a964ba0da/smos-cursor/src/Smos/Cursor/SmosFile.hs#L127. It's a bit stupid but it solved >80% of the problem so we've left it at that for now.

**Comment by NorfairKing** [comment]
The current situation should be about what you want in 95% of the cases now.
