### ISSUE TITLE
smos-calendar-import Fails With iCal Parse Error

### ISSUE THREAD

**Issue by jhbertra** [NorfairKing/smos#220]
## Steps to reproduce

1. Install `smos-calendar-import`
2. Configure a source for a Google calendar in `~/.smos/config.yaml` according to the config instructions https://docs.smos.online/smos-calendar-import
3. Run `smos-calendar-import`

## Expected result

Calendar is imported

## Actual result

Import fails with a parse error

```
➜  workflow git:(master) ✗ smos-calendar-import
Fetching: https://calendar.google.com/calendar/ical/<redacted>.ics
Error while parsing calendar from source: Personal Calendar
"https://calendar.google.com/calendar/ical/<redacted>.ics" (line 4707, column 1): parseAttachment: invalid value: Just "URI"
```

**Comment by NorfairKing** [comment]
Did you check whether the ical file was valid? Google sometimes spits out invalid ical files :(

**Comment by jhbertra** [comment]
I am looking through the ical file right now. Here is the offending line.

```
ATTACH;VALUE=URI:Basso
```

Apparently this is used to attach alarm sounds to events. What library is `parseICalendar` from? is it from https://hackage.haskell.org/package/iCalendar this package?

**Comment by jhbertra** [comment]
Based on the source code of `parseAttachment` - it definitely does not handle this value:

https://hackage.haskell.org/package/iCalendar-0.4.0.5/docs/src/Text.ICalendar.Parser.Properties.html#parseAttachment

**Comment by jhbertra** [comment]
After removing these lines from the ICal file, it imports. However, I have to download, save, and process the file before it can be imported, which isn't a good workflow. What is the best course of action here?

**Comment by NorfairKing** [comment]
> ```
> ATTACH;VALUE=URI:Basso
> ```

According to this part of the spec, it looks like that's not valid.
https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.1.1

 
> Apparently this is used to attach alarm sounds to events. What library is `parseICalendar` from? is it from https://hackage.haskell.org/package/iCalendar this package?

Technically it's from here, but yes: https://github.com/NorfairKing/ICalendar

> After removing these lines from the ICal file, it imports. However, I have to download, save, and process the file before it can be imported, which isn't a good workflow. What is the best course of action here?

In the past we (my clients and I) have solved this problem by removing the calendar event (and recreating it, if it's important).
Also: Please complain _loudly_ to whomever sent you the ics file :D

**Comment by NorfairKing** [comment]
Closing this as "Bug in google calendar, not in smos." for now.
We may want to write a more permissive parser at some point, but the world would become a worse place for it, so I'm not sure it's a good idea yet.

**Comment by jhbertra** [comment]
Confirmed that deleting these few events solved the problem. They were all pretty old, might have been some legacy data. Thanks again!
