### ISSUE TITLE
Aggregating clock entries for subtasks?

### ISSUE THREAD

**Issue by jhbertra** [NorfairKing/smos#222]
One of my recent projects has involved me splitting a single TODO into multiple ones under it. I like the organizational aspect and the progress indicator of this kind of fine-grained structure, but I am wondering if there is a way to aggregate clock entries for sub-tasks?  I have logged time under each sub-task, but the total time spent on the larger task isn't visible in any obvious way. It would be nice to see the aggregate time spent at various levels of a project hierarchy (project level, task level, subtask level).

My thoughts are that this could either be represented by an additional computed timestamp on forest entries, or shown in a report (maybe it is, and I'm just unaware of it?)

**Comment by NorfairKing** [comment]
The `smos-query clock` command does this for you. Have you had a chance to try it?

**Comment by jhbertra** [comment]
No, I have not, thanks!

**Comment by NorfairKing** [comment]
Feel free to reopen if necessary!
