### ISSUE TITLE
smos static binary unable to find terminfo in system locations

### ISSUE THREAD

**Issue by jlombera** [NorfairKing/smos#230]
Got following error when running released (0.3.1) static binary:

    $ echo $TERM
    xterm-256color

    $ smos foo.smos
    smos: setupTerm: Couldn't look up terminfo entry "xterm-256color"

    $ TERM=xterm smos foo.smos
    smos: setupTerm: Couldn't look up terminfo entry "xterm"

I am using Debian Linux testing:

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux bookworm/sid
    Release:	testing
    Codename:	bookworm

It looks like the binary tries to search in hardcoded Nix store location (which is missing in my systems since I don't use Nix) and doesn't try system locations:

    $ strace smos foo.smos 2>&1 | grep terminfo
    stat("/home/jlombera/.terminfo", 0x7ffc799dd908) = -1 ENOENT (No such file or directory)
    stat("/nix/store/ffx29fzq8zy0ihx2k2d2vk4lmgmj20gx-ncurses-6.2-x86_64-unknown-linux-musl/share/terminfo", 0x7ffc799dd908) = -1 ENOENT (No such file or directory)
    writev(2, [{iov_base="setupTerm: Couldn't look up term"..., iov_len=59}, {iov_base=NULL, iov_len=0}], 2setupTerm: Couldn't look up terminfo entry "xterm-256color") = 59

**Comment by NorfairKing** [comment]
Yup it looks like this is just very broken. I'm removing the static builds in #229

**Comment by jlombera** [comment]
@NorfairKing so, after #229, anyone wanting to use smos will have to build it with Nix?

BTW, since the static binary looks into `~/.terminfo`, I was able to workaround this by making `~/.terminfo` a symlink to `/lib/terminfo/`.

**Comment by NorfairKing** [comment]
@jlombera you can still build with stack ! See https://docs.smos.online/building-installation

**Comment by jlombera** [comment]
Oh, I see.  Thanks.
