### ISSUE TITLE
[feature request] export smos to org mode files

### ISSUE THREAD

**Issue by contrun** [NorfairKing/smos#238]
Currently, it is only possible to import org mode files to smos. Can we also have smos exported to org mode files?

**Comment by NorfairKing** [comment]
Should be pretty easy to write using `smos-data`, go for it!

**Comment by NorfairKing** [comment]
@contrun Please let me know if you do!

**Comment by contrun** [comment]
@NorfairKing I'd love to implement it. But I currently don't have much time. I can't say anything definitely.
