### ISSUE TITLE
"Projects without next actions" shows all projects  when the top level node has no TODO state

### ISSUE THREAD

**Issue by tgoossens** [NorfairKing/smos#242]
The recently introduced feature to show "Projects without next actions" has a bug.
Here is an example to reproduce it:

The following project is incorrectly listed as "a project without next action"
![Screenshot_select-area_20220507140528](https://user-images.githubusercontent.com/2463585/167271849-9eb6f0bd-0670-4d41-a13e-6739b37f542b.png)

The following project is correctly NOT listed as "a project without next action"
![Screenshot_select-area_20220507141215](https://user-images.githubusercontent.com/2463585/167271856-207d2ed2-940c-44fc-bf5b-0d7e68dd336e.png)

**Comment by NorfairKing** [comment]
@tgoossens Could you try out [d32be99](https://github.com/NorfairKing/smos/commit/d32be993ecdae3d97cc2261a4436c249bd79aaaf) and let me know if it fixes your issue?

**Comment by tgoossens** [comment]
That works!!

**Comment by NorfairKing** [comment]
Fixed on development.
