### ISSUE TITLE
b* commands do not work when there are no files

### ISSUE THREAD

**Issue by ursi** [NorfairKing/smos#249]
before adding a file, `bc`, `br`, `bp`, `bs` (and probably any others if they exist) do not work.

After adding a single file, you can use a single `b*` command to go somewhere, but once you're there, all non-`bw` `b*` commands don't work.

**Comment by NorfairKing** [comment]
Jup, there's an `ensureDir wd` missing here:
https://github.com/NorfairKing/smos/blob/cf1669f353dce8c5d5fc2f378a89a9bc945f3f0b/smos/src/Smos/Actions/Browser.hs#L283
PR welcome.

**Comment by NorfairKing** [comment]
It turns out this was a real directory switching bug and not just a missing `ensureDir`!
