### ISSUE TITLE
Self-sufficient `nix build` is not self-sufficient

### ISSUE THREAD

**Issue by ksenia-portu** [NorfairKing/smos#251]
@NorfairKing 
I wanted to mention, that `nix build` which supposed to be sufficient for running the server itself via:
```
$ nix build .#
$ nix develop
nix $ feedback web-server
```

on my machine (nixos-23.05) still requires 2 more steps:
```
cp -r ./result/bin/smos-web-server ~/.local/bin/.
cp -r ./result/bin/smos-server ~/.local/bin/.
```

Probably such instructions need to be added to *.nix

**Comment by NorfairKing** [comment]
This line is supposed to do that, you definitely don't want to use `cp -r ./result/bin/smos-web-server ~/.local/bin/`.
Did the `stack install` command succeed?

https://github.com/NorfairKing/smos/blob/82b5121c1f1462159c20d8012b5a89b4c772dcb3/feedback.yaml#L24

**Comment by ksenia-portu** [comment]
@NorfairKing
there were no notification that
```stack install``` command didn't succeed,
but since there is nothing related to `smos` in 
```.local/bin``` I believe it didn't succeed

**Comment by NorfairKing** [comment]
I can't reproduce this issue.
Feel free to reopen if the instructions here don't work as intended: https://docs.smos.online/development/contributing/smos-web-server
