### ISSUE TITLE
marketing / docs: consider adding more info about why smos vs orgmode / task warrior etc?

### ISSUE THREAD

**Issue by ym-han** [NorfairKing/smos#254]
I was quite intrigued by smos, but had to search reddit to find useful threads like https://www.reddit.com/r/orgmode/comments/ivlczu/smos_a_comprehensive_selfmanagement_tool/ that summarized why one might want to use smos instead of, e.g., orgmode --- I couldn't find a succinct comparison of the features / pros and cons of smos vs orgmode / task warrior etc anywhere in the docs. Hence my quick suggestion: If you want people to try smos out, it might be worth having this sort of summary somewhere prominent in the docs or landing page. (I'm guessing it's just because you are still working on the software itself and haven't quite got around to marketing yet, but just wanted to mention this just in case.)

**Comment by NorfairKing** [comment]
@ym-han PR welcome! There's this page but lots more has been added since I originally wrote that: https://docs.smos.online/features

There's also these: https://cs-syd.eu/tags/smos
