### ISSUE TITLE
Browser: allow swapping projects up and down in list

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#255]
It is possible to move ("swap" in smos parlance) entries within a project, however, not projects or other files within the browser. 

Since it is possible to insert projects in a specific place (using `n` or `N`, etc.) in the browser it appears there is some concept of manual ordering so I'm not sure how difficult this would be to implement.

**Comment by NorfairKing** [comment]
@distefam There is no manual ordering AFAIR. The files/appear in alphabetical order. When you insert a file/dir in a new place, it is temporarily inserted there.
When you reopen the browser it will be alphabetical again.
Manually ordering files and dirs makes little sense IMO, they're just files and dirs with a path.
