### ISSUE TITLE
Create projects from template without a schedule

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#266]
I'd like to be able to create a project from a template file without having to have a schedule. Essentially, run `smos-scheduler now template.smos` or something like that.

Reason: customer onboarding. I go through a pretty standard checklist of tasks that I have to do when I onboard a new business customer. Right now, I have that checklist outside of smos while managing the project of onboarding that user within smos. But, it would be really great to be able to just run a smos command to generate a new file for every new customer.

**Comment by NorfairKing** [comment]
Check the `sample` command for that tool.

**Comment by distefam** [comment]
That's perfect. The name sample led me to believe that it was just writing an example file so I never checked the help for the `sample` command. Does just what I wanted. Thank you.
