### ISSUE TITLE
Filenames/paths appear truncated in "interactive next action report"

### ISSUE THREAD

**Issue by aniketd** [NorfairKing/smos#28]
Step to reproduce:
1. `smos`
2. `rn`

result...
![2020-02-11-140634_554x380_scrot](https://user-images.githubusercontent.com/922486/74221390-080df200-4cd8-11ea-8665-c5ce8ff177a2.png)
The image is cropped on the right side. This is the result despite having a wide enough monitor to fit more information.

Possible solution:
  simple:
    Have the truncation be based on a percentage of total width of the screen, but always truncating only from the left (start of the filepath) and never truncating from the right (end of the filepath that typically includes the final filename)
  complex:
    Have the full path show in a limited width by rotating text, like web-banners from the 90's :stuck_out_tongue: (only half joking)

**Comment by NorfairKing** [comment]
Fixed in 10c3213
