### ISSUE TITLE
Error on Ubuntu the nix-shell

### ISSUE THREAD

**Issue by hackeryarn** [NorfairKing/smos#3]
## Ubuntu Error

I get the below error when I try to run `stack install :smos` on ubuntu. Any suggestions?

```
 [21 of 36] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Graphics/Vty/Input/Loop.o )
    <command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)
```

## Nix Error
 I also tried to run it in a `nix-shell`, but get the below error when `nix-shell` is trying to start.

```
evaluating file '/home/hackeryarn/dev/smos/nix/overlay.nix'
error: Please be informed that this pseudo-package is not the only part of
Nixpkgs that fails to evaluate. You should not evaluate entire Nixpkgs
without some special measures to handle failing packages, like those taken
by Hydra.
```

**Comment by NorfairKing** [comment]
Hi @hackeryarn I'm unsure about how to use `default.nix`, so what you tried won't work.
However, you can do this: `nix-shell -A haskellPackages.smos`

**Comment by hackeryarn** [comment]
@NorfairKing Thanks for the advice. That helped me get it running to try it out.

I will try to get the Ubuntu issue resolved and post the solution here. That way myself and other can hack on it.

**Comment by NorfairKing** [comment]
@hackeryarn Let me know how you fixed it on ubuntu, I will add a troubleshooting section to the Readme.

**Comment by hackeryarn** [comment]
The only way I found to fix this is by re-installing nix. Once I did that everything worked fine.

**Comment by NorfairKing** [comment]
I have a feeling it wasn't smos' fault then. Thanks for checking!
