### ISSUE TITLE
`smos-sync-client` does not create the workflow dir if it doesn't exist yet.

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#35]
In particular, the sync client fails if the workflow dir doesn't already exist.

**Comment by ketzacoatl** [comment]
Is the workflow dir `syncFlagContentsDir`? or where abouts would that step be added? in `syncSmosSyncClient` or alongside that function?

**Comment by NorfairKing** [comment]
@ketzacoatl I added a bit of an extra comment.  I think the problem is with reading the files before the sync instead of writing after the sync. If you look at the flags with `--help`, it's `--contents-dir`, yes.

**Comment by NorfairKing** [comment]
The first step would be to write a failing test case. The fix is likely just a single `forgivingAbsence`.

**Comment by NorfairKing** [comment]
Failing testcase in `06be1c4`

**Comment by NorfairKing** [comment]
fixed on development
