### ISSUE TITLE
smos-single confusing behaviour

### ISSUE THREAD

**Issue by wfranzini** [NorfairKing/smos#44]
When invoked with two arguments, TASK and FILEPATH, a file is created
under workflow with the name derived from the **concatenation** of
TASK and FILEPATH (lowercased) even if a file named FILEPATH already
exists.

**Comment by NorfairKing** [comment]
@wfranzini I didn't end up using smos-single, but it is indeed strange behavour.
It's another one line fix. I'll get to it.

**Comment by NorfairKing** [comment]
@wfranzini Try it out and see if this makes more sense now, please. Reopen if necessary.
