### ISSUE TITLE
sync-client: Wrong Cookie Gets Saved When Using with Cloudflare

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#45]
Essentially the same as https://github.com/NorfairKing/intray/issues/6

`smos-sync-client` ends up saving the `__cfduid` cookie instead of the `JWT-Cookie`:
```
$ cat .smos/sync-session.dat
__cfduid=REDACTED; Path=/; Expires=Tue, 19-May-2020 11:19:28 GMT; Domain=.REDACTED.com; HttpOnly; Secure
```

Switching cloudflare off, logging the sync client in via http, and then re-enabling cloudflare lets us circumvent this, but then credentials are sent over http.

**Comment by NorfairKing** [comment]
https://github.com/NorfairKing/smos/blob/53e1f37a06f16f2b32452ba0cc736e3707eb268a/smos-client/src/Smos/Client.hs#L42

Could the problem be here? I never understood why there were two headers there.
