### ISSUE TITLE
TUI Should Allow Navigating Between Files

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#48]
From my comments on #39:

It would be great if we had some way to navigate between our non-project and project files from within the `smos` TUI. I keep a single instance of smos running 24/7 so it was generally easier to keep a large file with all my tasks instead of having to quit smos & re-launch it with a different file.

The way to do this that comes to mind is to have a "file sidebar" that contains the general files & project files in the smos directory. With a naming scheme or nested project directories, we could also render the files in a collapsable tree.

E.g., if we have `projects/work_sese_issue-916.smos` & `projects/work_sese_issue-222.smos`(or flip the `-` & `_` or directories like `projects/Work/SESE/Issue\ 222` etc), it could be rendered as:
```
- Work
|- Sese
 |- Issue 222
 |- Issue 916
```

With each level being able to collapse it's child items.

We'd want to be able to allow users to disable this functionality. Maybe with a config setting like `show-sidebar :: Bool`, or defaulting the sidebar to being hidden when smos is started(with an option to change the default visibility).

How do we deal with general & project files that share the same file name? Should we have separate sections for the general & project files? Or show all general files first & then the project files?

Some potential keybindings:

*global*
* hide/show the sidebar
* switch focus between sidebar & task list

*sidebar*
* go to top/bottom of list
* move up/down the list
* collapse/uncollapse a tree
* create a new project as a sibling of the current item
* create a new project nested under the current item
* archive the focused project
* delete the focused project
* nest/un-nest the focused project

*task list*
* jump back in the project history(e.g., open work.smos, then switch to personal.smos. Then press `ctrl-o` to jump back from personal.smos to work.smos)
* jump forward in the project history

The other way we could handle this is with some file-search mechanism similar to the Ctrl-P or fzf vim plugins. I.e., press a keybinding to pop open a list of files & a search input. When text is entered, (fuzzy?) filter the file list, add keybindings for focusing an item in the returned list, and add a binding for switching to the focused file.

**Comment by NorfairKing** [comment]
> From my comments on #39:
> 
> It would be great if we had some way to navigate between our non-project and project files from within the `smos` TUI. I keep a single instance of smos running 24/7 so it was generally easier to keep a large file with all my tasks instead of having to quit smos & re-launch it with a different file.

I agree this would be fun. The interactive next-action report should already get you most of the way there.
Try running `reportNextActions`. `rn` by default.

> The way to do this that comes to mind is to have a "file sidebar" that contains the general files & project files in the smos directory. With a naming scheme or nested project directories, we could also render the files in a collapsable tree.

This seems like a cool idea to me, but I'd like to get the rest of the interactive reports out before we do this so that we can see how necessary this still is.

> E.g., if we have `projects/work_sese_issue-916.smos` & `projects/work_sese_issue-222.smos`(or flip the `-` & `_` or directories like `projects/Work/SESE/Issue\ 222` etc), it could be rendered as:

That seems silly. Just make subdirectories.

> ```
> - Work
> |- Sese
>  |- Issue 222
>  |- Issue 916
> ```
> 
> With each level being able to collapse it's child items.
> 
> We'd want to be able to allow users to disable this functionality. Maybe with a config setting like `show-sidebar :: Bool`, or defaulting the sidebar to being hidden when smos is started(with an option to change the default visibility).

Defaulting to hidden seems sensible to me.
We can also implement something like a startup hook in case you want to be able to configure the sidebar to be shown on startup.

> How do we deal with general & project files that share the same file name? Should we have separate sections for the general & project files? Or show all general files first & then the project files?

I'm not sure what you mean.
Project files are in the projects dir so we can just show a dir tree.

> Some potential keybindings:
> 
> _global_
> 
>     * hide/show the sidebar
> 
>     * switch focus between sidebar & task list
> 
> 
> _sidebar_
> 
>     * go to top/bottom of list
> 
>     * move up/down the list
> 
>     * collapse/uncollapse a tree
> 
>     * create a new project as a sibling of the current item
> 
>     * create a new project nested under the current item
> 
>     * archive the focused project
> 
>     * delete the focused project
> 
>     * nest/un-nest the focused project
> 
> 
> _task list_
> 
>     * jump back in the project history(e.g., open work.smos, then switch to personal.smos. Then press `ctrl-o` to jump back from personal.smos to work.smos)
> 
>     * jump forward in the project history

This is exactly what I needed.
If you want to go further with this, the next thing you'd do is to create a new cursor that has functions for each of these.
You'll need to either
1. create a dirtree cursor
or (easier)
2. use a map cursor.

I've put some work into a dirtree cursor on the `dirtree-refactor` branch, but that branch doesn't actually build yet.

> The other way we could handle this is with some file-search mechanism similar to the Ctrl-P or fzf vim plugins. I.e., press a keybinding to pop open a list of files & a search input. When text is entered, (fuzzy?) filter the file list, add keybindings for focusing an item in the returned list, and add a binding for switching to the focused file.

You'll definitely enjoy the interactive next-action report then.
I agree, this would be cool too.

**Comment by prikhi** [comment]
> The interactive next-action report should already get you most of the way there.

Yeah, I've been mostly using the `next` report directly from `smos-query` but noticed that <kbd>Enter</kbd> on the interactive version will jump you to the task in that file. So I'll start playing around w/ splitting up my files and using the interactive next report. I had also assumed that it only showed `NEXT` items but I see that `STARTED` are included which helps a lot as well.

> I'd like to get the rest of the interactive reports out before we do this so that we can see how necessary this still is

I did some googling earlier & I noticed you had this up as a Summer of Code project. Feel free to ping me if no one picks it up, it seems like a good way to get started w/ poking around in the codebase.

> That seems silly. Just make subdirectories.

Yeah that's what I was leaning towards once I wanted some customization on the names. I just wasn't sure if people generally grouped their project files by folder or kept them all in a single projects folder with filename prefixes.

> I'm not sure what you mean.
> Project files are in the projects dir so we can just show a dir tree.

Don't worry about it, a directory tree seems better than what I was imagining anyways :stuck_out_tongue: 

> If you want to go further with this, the next thing you'd do is to create a new cursor that has functions for each of these.

Cool, I may start poking around w/ it when I get some of these tasks that have been lingering around in my brain done with :)

**Comment by NorfairKing** [comment]
>  I did some googling earlier & I noticed you had this up as a Summer of Code project. Feel free to ping me if no one picks it up, it seems like a good way to get started w/ poking around in the codebase.

No one picked it up :(
     

> Cool, I may start poking around w/ it when I get some of these tasks that have been lingering around in my brain done with :)


No hurries. I'll be here to help.

**Comment by NorfairKing** [comment]
![dirforest-cursor](https://user-images.githubusercontent.com/3521180/82669257-70eff900-9c3b-11ea-88b8-acc7bb3edb8c.png)
@prikhi Just so you know: I'm working on this:
- https://github.com/NorfairKing/dirforest
- https://github.com/NorfairKing/cursor-dirforest

**Comment by prikhi** [comment]
Cool, I started poking around the source to see how I would implement an Agenda Report, but I'll probably comment on a new ticket(or should I piggyback on #26?) soonish looking for some guidance.

**Comment by NorfairKing** [comment]
@prikhi Cool, Let's use the new #55

**Comment by NorfairKing** [comment]
@prikhi I'm woring on the file browser and I've already got this:
![Peek 2020-05-24 02-51](https://user-images.githubusercontent.com/3521180/82743284-806d6000-9d69-11ea-9052-5ee4337f19cf.gif)

I'm working on the `file-browser` branch right now but I haven't pinned all the versions yet so you won't be able to use it just yet.

**Comment by NorfairKing** [comment]
@prikhi It's now ready to try out on `development`!

**Comment by NorfairKing** [comment]
I'm closing this for now. If the current solution can be improved, feel free to make more issues.
