### ISSUE TITLE
Add Automatic Creation of Recurring Tasks to Scheduler

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#49]
From comments on #39:

>>  How do you deal with recurring tasks(is that what the scheduler is for?)? Ideally, there'd be 2 types of recurring tasks. Those that repeat on fixed periods or those that repeat a fixed time after marking the previous occurrence as done. E.g., I have an "Enter Bank Statements" task in Finances that is scheduled for the 1st of the month. When I mark it as done, I create a duplicate task and schedule it for the first of the next month. For the second type, say I want to clean or organize weekly. After marking a "sweep!" task as done, I'd like to auto-add another "sweep!" task that is auto-scheduled on today + 7 days. But again, I feel like there'd be a clutter of DONE tasks after months of usage - maybe I should split it into projects by year, e.g. finances-2020.smos?
>
> Yes that's what the scheduler is for. It doesn't work yet, but feel free to write up an issue.
I agree with your multiple types of recurring tasks. I call them hairdresser-recurrent and rent-recurrent.
I'd like to get some more time to work on the scheduler but life gets in the way :)
Currently I have put a task in my weekly review template (that I copy around during the previous weekly review) to create a project to pay my bills (from another template).
So I'd have bills-17.smos for the bills project of the 17th week of the year.

Essentially, I'd like to automatically add new tasks on specific periods(e.g., start of next month, start of next quarter, start of next year) when a task is marked as done and after fixed durations(7 days after marking as done, 1 month after marking as done).

**Comment by NorfairKing** [comment]
This is not what the scheduler was designed for.
Instead the scheduler was made in order to automatically periodically create new projects.
The scheduler also has no knowledge of the previous instance of the same thing, so we can't do haircut-recurrence with it.

For now I recommend tickler.cs-syd.eu for the purpose of recurrent tasks.

I'd be happy if the scheduler _could_ do this though.

**Comment by prikhi** [comment]
> This is not what the scheduler was designed for.
> Instead the scheduler was made in order to automatically periodically create new projects.

Ah, guess I got confused by your reply. Pretty much all of the rent-recurring tasks I imagined scheduling would be in a new project per-batch(not added to an existing file) so I think that'd work for me. I don't have queued up any hairdresser-recurrent tasks yet, but I'll check out tickler when that time comes.
