### ISSUE TITLE
No cursor in normal mode

### ISSUE THREAD

**Issue by BlackCapCoder** [NorfairKing/smos#5]
There is no visual indication of where my cursor is in normal mode, so my current workflow is to move the cursor, then press `a<esc>` to see if the cursor is where I believe it is (there is a cursor in insert mode). This is a bit annoying, and I would hate for that habit spread into other vi-like software.

**Comment by NorfairKing** [comment]
@BlackCapCoder There is actually a cursor, but I have a feeling that you have a light color scheme.

![example](https://user-images.githubusercontent.com/3521180/48318837-4fee2700-e606-11e8-98a9-ab70f69b0efa.png)

I would like there to be a way to configure the colors that are being used but at the moment that doesn't exist yet. You could fork and modify the colors in the code for your own use, if you'd like to use `smos` with a light color scheme already.

**Comment by BlackCapCoder** [comment]
I actually use [pywal](https://github.com/dylanaraps/pywal) to generate dark color schemes based on my background image, and it just so happens that the color used for the cursor is always going to be the same as- or very slightly different from- the other `>` signs.

Anyways, this is the line to change in case anyone else is having this issue:
https://github.com/NorfairKing/smos/blob/980d3ee0c22b60ecbbf1efcde145719e4e6db553/smos/src/Smos/Style.hs#L61

**Comment by NorfairKing** [comment]
@BlackCapCoder The runtime-config color configuration is still underway but in the meantime I changed the sign in front of the non-selected headers to `-` so that you can still what's selected even if you have no colors.
