### ISSUE TITLE
Smos Should Reload Files After Syncing

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#50]
From comments on #39:

I usually have a smos TUI open 24/7. I also have systemd services & timers for running the sync-client every 10 minutes.

However, if the sync client pulls any updates to an open file, I need to close & re-open the TUI to show these changes. I'm also unsure what would happen if the sync-client updated a file and then I made changes & wrote to a file that was open before the sync-client was run(data-loss I'm assuming?).

I have used the [fsnotify](https://www.stackage.org/lts-15.10/package/fsnotify-0.3.0.1) library for writing file-watching build scripts, and it could probably be used to address this issue. We could watch for changes to the file that is currently open, but it might be difficult to differentiate between changes from the sync-client & changes from the TUI. 

Perhaps we could have every TUI instance watch the `sync-metadata.sqlite3` file instead, and reload their current files when we detect the sync database has been modified?

**Comment by NorfairKing** [comment]
> From comments on #39:
> 
> I usually have a smos TUI open 24/7. I also have systemd services & timers for running the sync-client every 10 minutes.
> 
> However, if the sync client pulls any updates to an open file, I need to close & re-open the TUI to show these changes. I'm also unsure what would happen if the sync-client updated a file and then I made changes & wrote to a file that was open before the sync-client was run(data-loss I'm assuming?).

That's right.
Whoever syncs to the server first wins. (This is fixable too, because we're using `mergeful`, but then we need to find a good `SmosFile -> SmosFile -> SmosFile` function that can merge things sensibly.)
Then when smos exits, it overwrites and that becomes the new latest state.

> I have used the [fsnotify](https://www.stackage.org/lts-15.10/package/fsnotify-0.3.0.1) library for writing file-watching build scripts, and it could probably be used to address this issue. We could watch for changes to the file that is currently open, but it might be difficult to differentiate between changes from the sync-client & changes from the TUI.

Just watching for the file that is currently open should just work.
Any change to the file on disk should be reloaded, right?
We could also have a mode that you can turn on where this doesn't happen and turn off that mode by default.

> Perhaps we could have every TUI instance watch the `sync-metadata.sqlite3` file instead, and reload their current files when we detect the sync database has been modified?

I'd rather keep `smos` and `smos-sync-client` independent. Just detecting file changes should be enough.

**Comment by prikhi** [comment]
> Just watching for the file that is currently open should just work.
> Any change to the file on disk should be reloaded, right?
> We could also have a mode that you can turn on where this doesn't happen and turn off that mode by default.

Seems sensible. I figured watching the file directly would cause reloads every time the running smos instance writes out to the file, but I suppose that's preferable compared to coupling `smos` & `smos-sync-client`.

**Comment by NorfairKing** [comment]
PR welcome
