### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#52]
Windows is currently not supported, mostly because I don't have any windows machines but I'm not opposed to it.

**Comment by NorfairKing** [comment]
I can confirm that using smos on Windows is possible via the WSL. Native windows support will not be possible because of https://github.com/jtdaugherty/brick/issues/46 and by extension https://github.com/jtdaugherty/vty/pull/1.

**Comment by tgoossens** [comment]
Experimental windows support was introduced in  commit fa500c2 

https://github.com/NorfairKing/smos/commit/fa500c2c54adda1eadb1cec091efae9eff32f19d
