### ISSUE TITLE
file browser: Nothing Happens When Opening Already-Open File

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#61]
1. Open an existing file in the workflow directory with smos
1. Open a new instance of smos & switch to the workflow file browser
1. Attempt to open the file in step 1 from the file browser

Result: Nothing happens in the 2nd smos instance

Expected: An error message is shown indicating that the file is already open?

**Comment by NorfairKing** [comment]
This should be do-able, but we currently have no mechanism for error messages because the file editor is a semantic editor so that was never necessary before.

**Comment by NorfairKing** [comment]
This shows an error now.
