### ISSUE TITLE
file browser: Jump to top / bottom of list

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#62]
Something like `gg` for top of the file browser & `G` for bottom would make navigation more consistent with the rest of the UI

**Comment by NorfairKing** [comment]
That would be nice. Easy too.
I think you could try to add that.

**Comment by prikhi** [comment]
Sure, I'll poke around in a couple of days.

**Comment by NorfairKing** [comment]
This has been done for a while now, but I forgot to close this issue.
