### ISSUE TITLE
file browser: Add Ability to Create New Smos Files

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#63]
Something like `e` for creating a new file at the current hierarchy level & `E` for creating a new file under the currently selected directory?

Maybe a workflow would be creating a blank line, adding the `.smos` file extension to it, and then moving the input cursor to the beginning of the line so we can simply type the desired file name?

Show an error if a file with the given name already exists?

**Comment by NorfairKing** [comment]
This would be nice but it has a bunch of problems that need solving first:

1. Ordering of files
2. Duplicate filenames
3. Filenames that are the same as a directory name

There are similar issues with #64.
I'm not sure what to do about these yet

**Comment by prikhi** [comment]
Yes, I had thought about the duplicate filenames. Maybe flash an error message in the header bar, or add a one-line status bar at the bottom showing the error, similar to vim's statusline?

Any ways, these are all just "extra-nice" or quality-of-life features. Smos is already plenty useful as it is :grin:

**Comment by NorfairKing** [comment]
@prikhi Thanks! It's been a lot of work. I hope to get it to the point where we can have external contributors and/or funding for me to justify spending more time on it.

**Comment by NorfairKing** [comment]
It turns out that this exact feature is actually more important than I expected it to be. @prikhi If you'd like to take a stab at it then I'd be happy to help.

**Comment by NorfairKing** [comment]
This is now in development. I haven't tested the duplicate filenames problem and the ordering of files problem is just being ignored at the moment.

**Comment by NorfairKing** [comment]
I'm leaving this issue open because of the duplicates and ordering problem.
Both can be fixed by enforcing an ordering on every level of the dirforest cursor, but this is not a trivial problem to solve.
