### ISSUE TITLE
time tracking: Show Indicator When Clocked In

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#65]
I like the clock in/out feature, but on occasion, I forget that I am clocked in and end up logged 24 hours to a task :grimacing: 

It would be cool if there was a "CLOCKED IN" indicator in the TUI to show me that I am currently logging time. Maybe on the right side of the filename header?

**Comment by NorfairKing** [comment]
This is already shown within the entry very prominently.
It's not possible in general because you'd have to continuously look at all files in the workflow dir.
Maybe there is some approximation inbetween.
