### ISSUE TITLE
TUI: Center Window on Currently Focused Task

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/smos#66]
It would be nice to have a command like vim's `zz`, which scrolls the view so that the currently focused line is in the center of the terminal. 

With larger files, I sometimes lose track of where the cursor is. Being able to set the color of the cursor(e.g., to magenta) would maybe make this unnecessary.

**Comment by NorfairKing** [comment]
We should be able to have colour themes relatively easily using brick's [Theme](https://hackage.haskell.org/package/brick-0.54/docs/Brick-Themes.html).
The scrolling like that is not supported l think: https://hackage.haskell.org/package/brick-0.54/docs/Brick-Main.html#t:ViewportScroll
