### ISSUE TITLE
Selecting the contents of the entry does not uncollapse the contents

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#76]
![Peek 2020-06-12 15-10](https://user-images.githubusercontent.com/3521180/84505976-ec831a00-acbe-11ea-83c8-14a71475ffd2.gif)

**Comment by gltronred** [comment]
There are bools for parts that can be collapsed, but no corresponding actions in `Smos.Action.*`: https://github.com/NorfairKing/smos/blob/master/smos-cursor/src/Smos/Cursor/Collapse.hs

I will add actions and bind them to `z<char>` (https://vim.fandom.com/wiki/Folding):
- `zc` - toggle contents visibility
- `zh` - toggle history visibility
- `zl` - toggle logbook visibility

**Comment by gltronred** [comment]
Actions for collapsing parts of entry are ready. But they do not solve the problem with selecting collapsed entry. 

I think that correct solution would be to forbid selecting contents if it is hidden. But it seems to be a lot of work to implement it

**Comment by NorfairKing** [comment]
> I think that correct solution would be to forbid selecting contents if it is hidden. But it seems to be a lot of work to implement it

You could auto-unfold the contents if the contents aren't selected. That's the way it works with making an entry below the current entry right now.

**Comment by NorfairKing** [comment]
This is now fixed on development.
