### ISSUE TITLE
Filters for the interactive next-action report

### ISSUE THREAD

**Issue by NorfairKing** [NorfairKing/smos#78]
The current next-action report doesn't admit any filters.
It would be nice if you could type `/` and then a filter.

**Comment by alomew** [comment]
As an update, I have added the text bar which accepts input etc. 
Tomorrow I will instrument the actual filtering, but I reckon I have most of the pieces ready.

**Comment by NorfairKing** [comment]
Awesome! Let me know if I can help!

**Comment by NorfairKing** [comment]
This exists now!
