### ISSUE TITLE
Scrolling is broken on `development`

### ISSUE THREAD

**Issue by CSVdB** [NorfairKing/smos#8]
Steps to reproduce the problem:
- open a smos file which is large enough so that the rendered tree doesn't fit on one terminal
  You can simply create empty headers by pressing 'h + esc' until the rendering doesn't fit the terminal.
- press 'gg' to go to the top of the page

You will notice that the cursor disappears (because it jumped up), but the viewbox doesn't change.

The viewbox does jump when you create a header ('h'), but not when you navigate using 'gg', 'G', 'j', 'k'.

**Comment by NorfairKing** [comment]
Thanks! I made a mistake during refactoring. Should be fixed now.

**Comment by CSVdB** [comment]
Thank you for the quick fix!
