### ISSUE TITLE
Error building(nix-build) on mac os

### ISSUE THREAD

**Issue by countoren** [NorfairKing/smos#81]
Failures:

  test/Data/DirForestSpec.hs:333:7: 
  1) Data.DirForest.readDirForest reads valid forests
       uncaught exception: IOException of type InvalidArgument /private/var/folders/0l/h15hb2l52js7j9yr_xlhzmfm0000gp/T/nix-build-genvalidity-dirforest-0.0.0.0.drv-0/dirforest-test-0fe76851c53ac1e2/a/񁳽: openBinaryFile: invalid argument (Illegal byte sequence)
       (after 2 tests and 4 shrinks)
         DirForest {unDirForest = fromList [("a",NodeDir (DirForest {unDirForest = fromList [("\269565",NodeFile "")]}))]}

  To rerun use: --match "/Data.DirForest/readDirForest/reads valid forests/"

  test/Data/DirForestSpec.hs:348:7: 
  2) Data.DirForest.readDirForest reads what was written
       uncaught exception: IOException of type InvalidArgument
       /private/var/folders/0l/h15hb2l52js7j9yr_xlhzmfm0000gp/T/nix-build-genvalidity-dirforest-0.0.0.0.drv-0/dirforest-test-9ca7fa3860d1b737/a/񁳽: openBinaryFile: invalid argument (Illegal byte sequence)
       (after 2 tests and 4 shrinks)
         DirForest {unDirForest = fromList [("a",NodeDir (DirForest {unDirForest = fromList [("\269565",NodeFile "")]}))]}

  To rerun use: --match "/Data.DirForest/readDirForest/reads what was written/"

  test/Data/DirForestSpec.hs:350:9: 
  3) Data.DirForest.writeDirForest works in a nonexistent root
       uncaught exception: IOException of type InvalidArgument /private/var/folders/0l/h15hb2l52js7j9yr_xlhzmfm0000gp/T/nix-build-genvalidity-dirforest-0.0.0.0.drv-0/dirforest-test-03e05b3db8f5b197/a/񁳽: openBinaryFile: invalid argument (Illegal byte sequence)
       (after 2 tests and 4 shrinks)
         DirForest {unDirForest = fromList [("a",NodeDir (DirForest {unDirForest = fromList [("\269565",NodeFile "")]}))]}

  To rerun use: --match "/Data.DirForest/writeDirForest/works in a nonexistent root/"

**Comment by NorfairKing** [comment]
Thanks ! This will help me to fix the macos build and set up a macos CI

**Comment by countoren** [comment]
we were able to make run by adding this flag to smos/package.ymal
```nix

executables:
  smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -optP-Wno-nonportable-include-path
   
```

**Comment by NorfairKing** [comment]
Super, thanks!

**Comment by NorfairKing** [comment]
Fixed! And we now have ci for macos
